In [10]:
import numpy as nb
#array 2 dimension
#des lignes et des colonnes
#ar[Lignes,Colonnes]
ar = nb.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#Afficher la ligne indice 1 et 2, et toutes les colonnes
ar[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [5]:
#récupère le sous-array des lignes 2 et 3, et des colonnes 1 et 2.
ar[1:3,0:2]


array([[4, 5],
       [7, 8]])

In [6]:
#renvoie la 2ème ligne, 
#mais l'array renvoyée n'a plus qu'une seule dimension
ar[1,:]


array([4, 5, 6])

In [7]:
#renvoie la 2ème ligne, 
#mais en conservant les 2 dimensions
ar[1:2,:]

array([[4, 5, 6]])

In [8]:
#renvoie la dernière colonne de chaque ligne 
#dans un array a une dimension
ar[:,-1]

array([3, 6, 9])

In [11]:
#renvoie la dernière colonne
#dans un array a une dimension
ar[-1]

array([7, 8, 9])

#on peut filtrer par valeur 
#renvoie le tableau avec des booléans
#true si condition est vrai sinon false
ar == 1

# Opérations sur les tableaux

In [25]:
import numpy as np
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A,B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

### Addition

In [26]:
#additionner 2 tableaux
#ligne par ligne et colonne par colonne
A+B

array([[3, 1],
       [3, 5]])

### Attention 
Il faut que les deux array est la même longueur de tableau et même forme
e.g : 
    si ar1[2lignes,3colonnes] il faut que le ar2 est [2lignes,3colonnes] pour pouvoire faire l'addition

### Soustraction

In [27]:
A-B

array([[-1,  1],
       [-3, -3]])

### Multiplication

In [28]:
A*B

array([[2, 0],
       [0, 4]])

### Division

In [31]:
C = A/B
C

<ipython-input-31-083dddd02419>:1: RuntimeWarning: divide by zero encountered in true_divide
  C = A/B


array([[0.5 ,  inf],
       [0.  , 0.25]])

In [32]:
C[0,-1]

inf

In [37]:
C[0,-1].dtype


dtype('float64')

# Les fonctions mathématiques de base¶


In [57]:
#min et max 
a = np.array([1.7,2.8,3])
a.min()
a.max()

3.0

In [49]:
#Renvoie les indices des valeurs maximales le long d'un axe
#https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
a.argmax(),a.argmin()

(2, 0)

In [50]:
nb.argmax(a),nb.argmin(a)

(2, 0)

In [58]:
#moyenne 
a.mean()

2.5

In [60]:
#somme
#axis = 0 ==> colonne1 de la ligne1 + colonne2 de la ligne2 ....
#axis = 1 ==>la somme de la ligne1 ...
b=np.array([[1, 2], [3, 4]])
b.sum(axis=0),b.mean(axis=1),b.sum(axis=1)

(array([4, 6]), array([1.5, 3.5]), array([3, 7]))

### Attention 
il faut que les lignes est la même longueur de tableau

In [63]:
#calculer la somme des valeur d'un tableau
nb.array([1,2,3,4]).cumsum()[-1]

10

In [64]:
#calculer la somme de toutes les valeurs dans un tableau 
b.cumsum()[-1]

10

In [65]:
#Calculer la somme des valeurs de chaque ligne dans un tableau à 2 dimension
b.cumsum(axis=1)[:,-1]

array([3, 7])

In [67]:
#position du max
b,np.argmax(b,axis=0)

(array([[1, 2],
        [3, 4]]),
 array([1, 1]))